# Generated by Django 6.0.5 on 2026-05-07 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('PM', 'PM Level'), ('CM', 'CM Level'), ('DISTRICT', 'District Level'), ('BLOCK', 'Block Level'), ('FIELD', 'Field Level')], default='PM', max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('FORWARDED', 'Forwarded'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ASSIGNED', 'Complaint Assigned'), ('STATUS_UPDATE', 'Status Updated'), ('SLA_BREACH', 'SLA Breached'), ('ESCALATION', 'Escalated'), ('FORWARDED', 'Forwarded'), ('RESOLVED', 'Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Admin'), ('PM', 'PM / Super Admin'), ('CM', 'CM / State Admin'), ('DISTRICT_OFFICER', 'District Officer'), ('BLOCK_OFFICER', 'Block Officer'), ('FIELD_OFFICER', 'Field Officer'), ('OFFICER', 'Officer')], default='CITIZEN', max_length=20),
        ),
        migrations.CreateModel(
            name='ForwardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(max_length=20)),
                ('to_level', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('FORWARD', 'Forward'), ('ESCALATE', 'Escalate'), ('ASSIGN', 'Assign')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_records', to='grievance_app.complaint')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
