# Generated by Django 4.2.13 on 2026-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0002_complaint_block_complaint_current_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('DEPARTMENT', 'Department / Nodal Officer'), ('PM', 'PM Level'), ('CM', 'CM Level'), ('DISTRICT', 'District Level'), ('BLOCK', 'Block Level'), ('FIELD', 'Field Level')], default='DEPARTMENT', max_length=15),
        ),
    ]
