# Generated by Django 4.2.13 on 2026-05-08 09:53

from django.db import migrations, models


def collapse_legacy_roles(apps, schema_editor):
    User = apps.get_model("grievance_app", "User")
    Complaint = apps.get_model("grievance_app", "Complaint")

    User.objects.exclude(role__in=["ADMIN", "OFFICER", "CITIZEN"]).update(role="OFFICER")
    Complaint.objects.exclude(current_level__in=["DEPARTMENT", "OFFICER", "ADMIN"]).update(current_level="OFFICER")


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0005_department_parent_department_created_by'),
    ]

    operations = [
        migrations.RunPython(collapse_legacy_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('DEPARTMENT', 'Department Head / Officer'), ('OFFICER', 'Officer Level'), ('ADMIN', 'Admin Level')], default='DEPARTMENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Admin'), ('OFFICER', 'Officer')], default='CITIZEN', max_length=20),
        ),
    ]
